### ISSUE TITLE
Problem creating/cloning JSON files 

### ISSUE THREAD

**Issue by kreynen** [backdrop-ops/backdrop-pantheon#27]
@jenlampton and @quicksketch have mentioned that truncated json files were a known issue on Pantheon.  We've seen this when synchronizing files between environments as well as clean installs.  The sync error can manifest itself in a number of ways.  On install, the error has been a "ConfigStorageReadExeption: The configuration file 'system.core' is not properly formatted JSON."

![screen shot 2018-09-05 at 1 52 57 pm](https://user-images.githubusercontent.com/385234/45176582-ac2f6780-b1cd-11e8-92d7-03f1912bcc2d.png)

**Comment by alexfinnarn** [comment]
I've just tested out installing a site on Pantheon from https://dashboard.pantheon.io/sites/create?upstream_id=bf703821-4c18-45a1-88b8-3d9ec302273d, and I did not have issues cloning files and the database between live and dev environments in my limited testing. I'll add to this issue if I see anything more.

**Comment by jenlampton** [comment]
I've found that it's intermittent.

**Comment by herbdool** [comment]
@jenlampton is there an issue thread with more info on this? Have you found a workaround for now?

Is this when the active JSON is stored in the files directory or in the code?

**Comment by jenlampton** [comment]
The work-arrund is to keep copying the files until one time, the files
aren't mangled. It doesn't happen every time.

You can't have your live config directory outside the files directory on
Pantheon because the files directory is the only place that's web-writable.

**Comment by jenlampton** [comment]
Update: I haven't had any JSON file corruption on Pantheon now for more than a year. Perhaps there was some update to Valhala that fixed this problem...

Also new: There is a new web-writable directory outside the docroot now on Pantheon, I believe it is named `code`. It would be safe to keep configuration files in this directory. 

https://pantheon.io/docs/nested-docroot

**Comment by herbdool** [comment]
I do not believe it is web-writable, but someone could test this. Those files would still be part of the repo and the directories locked on test and live.

From what I understand, it would mean the structure would change from the current `code/index.php` to `code/web/index.php`.

**Comment by jenlampton** [comment]
> I do not believe it is web-writable, but someone could test this. 

On [the docs page](https://pantheon.io/docs/platform-considerations#compute-optimized-environments-coe) it says `Note that within the home directory, only /code, /files, and /tmp are writable.` 

This caught my eye because we'd been waiting for a web-writable directory other than `files` for a long time :)

**Comment by herbdool** [comment]
I'm going to test it, but first it seems I need to get a fix for spinning up a Backdrop site. I've asked Pantheon support to look into an error.

![Screenshot from 2020-06-19 15-39-51](https://user-images.githubusercontent.com/1071483/85174677-d687d300-b243-11ea-8c7c-8809e29bda52.png)

**Comment by herbdool** [comment]
I'm now wondering if we should deal with this at the source: https://github.com/backdrop/backdrop-issues/issues/4447. Mainly because this might be an issue for other hosts as well.

**Comment by herbdool** [comment]
@jenlampton I've now tested moving the webroot.

1. I've updated the `pantheon.yml` so that the webroot becomes `/web` so we have e.g. `/web/core`, `/web/index.php`. I was able to spin up a site.
2. Then I put it into git mode and then attempted to ftp a file up to `/code`. It fails. I suspected this because everything under code is the repository and is only writable in sftp mode.

I suspect they might have meant it was writable in sftp mode, but even then it's not really clear. I think they need to clarify that. It won't help with this problem.

**Comment by jenlampton** [comment]
I think they mean "writable" in the same way the `files` directory is "writable" (since they listed them together) meaning that the web server would be allowed to write to that directory. SFTP mode wouldn't be a good test for whether a directory is web-writable because with SFTP you're using your own user, not the web user (which I think on Pantheon is named `nginx`).

You could switch your "files" directory (via the UI) to "/code" and see if you can upload a file. That would be a good test.

**Comment by herbdool** [comment]
I contacted Pantheon support @jenlampton. Here's what they told me:

> The /code, /files, and /tmp directories are the only locations within a site's home directory that are writable by a customer in any scenario.
>
>However the only location in the fileserver that is "writable" by the website is wp-content/uploads/ (WordPress) or sites/default/files/ (Drupal) in Live and Test, as well as Dev and any multidev environments when they are in Git mode.
>
>These are both symlinks to the /files directory you'll see when you first log into the server via sftp.

They admitted that the sentence in the docs was a bit confusing.

**Comment by jenlampton** [comment]
Thanks @herbdool for getting to the bottom of that!  I'm sad that there's still no web-writable directory other than files :( Drupal 8 will need this too, for the auto-generated twig files, so I'm hoping Pantheon catches up with the times soon!

**Comment by herbdool** [comment]
@jenlampton not sure but I believe that was fixed for D8 here https://github.com/pantheon-systems/drops-8/pull/182/files

**Comment by herbdool** [comment]
@jenlampton I don't think it's a matter of catching up with the times, Pantheon and Platform.sh both lock down the code directory for security reasons. I think it was more about the nature of the file server which is symlinked.

**Comment by jenlampton** [comment]
> Pantheon and Platform.sh both lock down the code directory for security reasons

The files directory is already web-writable. There's no "security reason" we couldn't have two of them :/

**Comment by herbdool** [comment]
Yes files is writable, that's not in dispute. The point was that code/ can't be web writable because we don't want apps to change the code.

With Pantheon we can specify what gets stored in files/ but that still leaves it with the original issue here.

**Comment by jenlampton** [comment]
> The point was that code/ can't be web writable because we don't want apps to change the code.

We don't want external apps to change Backdrop's internal PHP code, sure, but there's no reason we can't **also** have a web-writable directory where we can save other things. The `files` directory proves that. On Pantheon the files directory happens to be a symlink to some other location, but on most systems it's simply a sub-directory that lives within the internal PHP code. (For drupal it usually lived at `sites/default/files`). 

My point was only that it would be possible to have a `sites/default/config` or just `config` configured in exactly the same way as the `files` directory without introducing any security issues. Pantheon and Platform might lock down all the directories, but it's not for "security reasons", I expect it's because they are more feature rich systems and doing it this way is the simplest and easiest solution. 

> but that still leaves it with the original issue here.

I don't think the original issue is still an issue, since JSON files aren't getting corrupted when the files directory is copied anymore?

Should we maybe close this and focus on https://github.com/backdrop/backdrop-issues/issues/4447 instead?

**Comment by herbdool** [comment]
I agree we can close this if you haven't experienced the problem in quite a while.
